name: CI-Docker

on:
  workflow_dispatch:         
  push:
    tags:
      - 'v*'                 

env:
  IMAGE_NAME: unsinnews/proxify
  PLATFORMS: linux/amd64,linux/arm64 # multi-arch support

jobs:
# ---------------------------------------------------------------- Build & Push Docker Image
  docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure run is based on tag
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          if [[ "$GITHUB_REF" != refs/tags/* ]]; then
            echo "[ERROR] This workflow must be triggered from a Git tag (refs/tags/v*)"
            exit 1
          fi

      - name: Extract version tag
        id: vars
        run: |
          VERSION="${GITHUB_REF##*/}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "[INFO] Tag version: ${VERSION}"

      # login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # set Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          file: ./Dockerfile
          context: .
        #   cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        #   cache-to: type=inline
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Display pushed image info
        run: |
          echo "Successfully pushed:"
          echo " - ${{ env.IMAGE_NAME }}:latest"
          echo " - ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}"

      - name: Re-push latest to bump it on top
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
